export const ADD_ITEM = 'ADD_ITEM'
export const ADD_STUDENT = 'ADD_STUDENT'
export const  DELETE_STUDENT = 'DELETE_STUDENT'
export const STUDENT_INFO = 'STUDENT_INFO'
export const  UPDATE_STUDENT = 'UPDATE_STUDENT'
